<!doctype html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Type The Classics</title>
        <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
        <style>
            * {
                box-sizing: border-box;
            }
            body {
                margin: 0;
                padding: 0;
                width: 100%;
                font-family: 'Droid Serif', sans-serif;
                text-align: center;
                color: #333;
                font-size: 18px;
            }
            #nav {
                width: 100%;
                height: 50px;
                border-bottom: 1px solid #ccc;
                margin-bottom: 10px;
            }
            #editor-input {
                opacity: 0;
                position: absolute;
                top: -999999px;
            }
            #display-container, 
            #editor-container {
                width: 90%;
                height: calc(50vh - 30px);
                padding: 20px 10%;
                font-size: 2em;
            }
            #display,
            #editor {
                position: relative;
                height: 100%;
                padding: 20px 25px;
            }
            #display {
                border: 1px solid #ccc;
            }
            #editor {
                border: 1px solid #ddd;
                white-space: pre-wrap;
            }
            #editor.active {
                border: 1px solid red;
            }
            #cursor {
                border-left: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
        <div id="nav" class="nav">

        </div>
        <div id="display-container"></div>
        <div id="editor-container"></div>

        <script src="js/bundle.js"></script>
    </body>
</html>
